### ISSUE TITLE
Warning issue in D10

### ISSUE THREAD

**Issue by kylehuynh205** [kylehuynh205/islandora_group#15]
````
Warning: Undefined array key "class" in Drupal\islandora_group\Utilities::isCalledFromBulkBatch() (line 720 of /var/www/D10-ecn/web/modules/contrib/islandora_group/src/Utilities.php)
#0 /var/www/D10-ecn/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real()
#1 /var/www/D10-ecn/web/modules/contrib/islandora_group/src/Utilities.php(720): _drupal_error_handler()
#2 /var/www/D10-ecn/web/modules/contrib/islandora_group/islandora_group.module(128): Drupal\islandora_group\Utilities::isCalledFromBulkBatch()
#3 [internal function]: islandora_group_node_update()
#4 /var/www/D10-ecn/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(409): call_user_func_array()
#5 /var/www/D10-ecn/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(388): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}()
#6 /var/www/D10-ecn/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(416): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#7 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(215): Drupal\Core\Extension\ModuleHandler->invokeAll()
#8 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(900): Drupal\Core\Entity\EntityStorageBase->invokeHook()
#9 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(564): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook()
#10 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(781): Drupal\Core\Entity\EntityStorageBase->doPostSave()
#11 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(489): Drupal\Core\Entity\ContentEntityStorageBase->doPostSave()
#12 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(806): Drupal\Core\Entity\EntityStorageBase->save()
#13 /var/www/D10-ecn/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save()
#14 /var/www/D10-ecn/web/core/modules/node/src/NodeForm.php(270): Drupal\Core\Entity\EntityBase->save()
#15 [internal function]: Drupal\node\NodeForm->save()
#16 /var/www/D10-ecn/web/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array()
#17 /var/www/D10-ecn/web/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers()
#18 /var/www/D10-ecn/web/core/lib/Drupal/Core/Form/FormBuilder.php(597): Drupal\Core\Form\FormSubmitter->doSubmitForm()
#19 /var/www/D10-ecn/web/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\Core\Form\FormBuilder->processForm()
#20 /var/www/D10-ecn/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#21 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#22 /var/www/D10-ecn/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#23 /var/www/D10-ecn/web/core/lib/Drupal/Core/Render/Renderer.php(592): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#24 /var/www/D10-ecn/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#25 /var/www/D10-ecn/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#26 /var/www/D10-ecn/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#27 /var/www/D10-ecn/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#28 /var/www/D10-ecn/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#29 /var/www/D10-ecn/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#30 /var/www/D10-ecn/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#31 /var/www/D10-ecn/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#32 /var/www/D10-ecn/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#33 /var/www/D10-ecn/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#34 /var/www/D10-ecn/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#35 /var/www/D10-ecn/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#36 /var/www/D10-ecn/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#37 {main}
````

**Comment by Natkeeran** [comment]
No longer an issue!
